// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3vBvEFgfa_ppOPMGvWmbj_14kMl37un4',
    appId: '1:52361736442:web:c8b8e684f5e76a30011943',
    messagingSenderId: '52361736442',
    projectId: 'printinghub-207bd',
    authDomain: 'printinghub-207bd.firebaseapp.com',
    storageBucket: 'printinghub-207bd.firebasestorage.app',
    measurementId: 'G-VM1DYTM6HJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2VWhBSxu49YhzOw5XmC8FS29MRvZRMqg',
    appId: '1:52361736442:android:f282fd08ef4c9ee1011943',
    messagingSenderId: '52361736442',
    projectId: 'printinghub-207bd',
    storageBucket: 'printinghub-207bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPVmKeO5rckkXgmO05GSpvgiXxlb2pU6I',
    appId: '1:52361736442:ios:95fe1bda91b27e07011943',
    messagingSenderId: '52361736442',
    projectId: 'printinghub-207bd',
    storageBucket: 'printinghub-207bd.firebasestorage.app',
    iosClientId: '52361736442-jv6o760glsbjqeburj5e2gmr753deq2g.apps.googleusercontent.com',
    iosBundleId: 'com.google.firebase.presents.cityprint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPVmKeO5rckkXgmO05GSpvgiXxlb2pU6I',
    appId: '1:52361736442:ios:95fe1bda91b27e07011943',
    messagingSenderId: '52361736442',
    projectId: 'printinghub-207bd',
    storageBucket: 'printinghub-207bd.firebasestorage.app',
    iosClientId: '52361736442-jv6o760glsbjqeburj5e2gmr753deq2g.apps.googleusercontent.com',
    iosBundleId: 'com.google.firebase.presents.cityprint',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3vBvEFgfa_ppOPMGvWmbj_14kMl37un4',
    appId: '1:52361736442:web:7bb7842f3933589a011943',
    messagingSenderId: '52361736442',
    projectId: 'printinghub-207bd',
    authDomain: 'printinghub-207bd.firebaseapp.com',
    storageBucket: 'printinghub-207bd.firebasestorage.app',
    measurementId: 'G-1VGSDPQVYS',
  );
}
